### ISSUE TITLE
Pre-built JS package

### ISSUE THREAD

**Issue by tpluscode** [pbonte/roxi#17]
Would it be possible to provide a JS build on NPM so that the manual WASM compilation and installation from a local dir would not be necessary?

Looks like a low-hanging fruit

Happy to attempt a PR :)

**Comment by pbonte** [comment]
Hi @tpluscode,

Thanks for you interest in RoXi!

It was indeed on my todo list to add it to NPM and you were just the little push I needed to make it a priority! Thanks!

You can find it the JS bindings here: [https://www.npmjs.com/package/roxi-js](https://www.npmjs.com/package/roxi-js?activeTab=readme)

KR,
Pieter

**Comment by tpluscode** [comment]
Wow, that was fast. Thank you so much
