### ISSUE TITLE
Reasonable: DataFrog based OWL reasoner

### ISSUE THREAD

**Issue by ktk** [pbonte/roxi#23]
Just a FYI, this was mentioned yesterday in a W3C call https://github.com/gtfierro/reasonable

I wonder how related this is, are you doing your own reasoning engine in roxi? This one seems to be DataFrog based.

Feel free to close issue immediately.

**Comment by pbonte** [comment]
Hi @ktk ,

I remember checking it out before I started roxi, however, as it has been some time I don't remember much details.
I guess it is translating OWL2 RL inference to a datalog program that is evaluated with DataFrog.

Roxi has its own inference reasoner built from scratch, allowing research on the optimization of inference algorithms and datastructures. This flexibility also allows us (in theory) to support more expressive reasoning than OWL2 RL. (However, this is not implemented yet)

Hope this helps.

KR,
Pieter
