### ISSUE TITLE
Implementing the bindings in a hashmap which works with the webassembly Nodejs Map.

### ISSUE THREAD

**Issue by argahsuknesib** [pbonte/roxi#6]

**Comment by pbonte** [comment]
It was a bit more complicated because you had to convert between Rust/wasm/JSvalues, see https://github.com/pbonte/roxi/blob/de60a6e3531d7f7ac7ad359d9d90c13fca14ad29/js/src/lib.rs#L91

So I quickly did it myself.
There is not a JSBinding class you can use
