### ISSUE TITLE
Support for using `a` instead of `<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>`

### ISSUE THREAD

**Issue by maartyman** [pbonte/roxi#9]

**Comment by argahsuknesib** [comment]
not sure if there are exisiting packages for this, but I am doing this by making a Vocabulary directory where you can write.
```
export const RDF = createUriAndTermNamespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#',
    'type');
```
and do a  ```RDF.type```

**Comment by pbonte** [comment]
@maartyman , is this when defining the query, the rules or just the abox data?

**Comment by pbonte** [comment]
I changed the syntax to Turtle, but there is support for NTriples, Turtle and Trig. Maybe we should add some selection box?

**Comment by pbonte** [comment]
Yes, NTriples can be expressed in Turtle, but not the other way around. The `a` shorthand is only valid in Turtle.

**Comment by maartyman** [comment]
Okay so just a switch between Turtle and Trig then?

**Comment by pbonte** [comment]
I would do all 3 of them, because NTriples is faster to parse

**Comment by maartyman** [comment]
An extension to this issue is not only that you can't use ´a´ in NTriples. But also that you can't use rdf:type in the A-Box and ´a´ in the rules, like in [this](https://pbonte.github.io/roxi/index.html?view=reasoning&abox=%3Chttp%3A%2F%2Fexample2.com%2Fa%3E%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%3E%20%3Chttp%3A%2F%2Fwww.test.be%2Ftest%23SubClass%3E%20.&rules=%40prefix%20test%3A%20%3Chttp%3A%2F%2Fwww.test.be%2Ftest%23%3E.%0A%20%7B%3Fs%20a%20test%3ASubClass.%20%7D%3D%3E%7B%3Fs%20a%20test%3ASuperType.%7D) simple example.

**Comment by pbonte** [comment]
Thanks for noticing! Extended the n3 parser and added a test case. Should work now
